version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              command: npm install
              working_directory: backend
            - run:
              command: npm test
              working_directory: backend
workflows:
  build-and-test:
    jobs:
      - build-and-test-backend
